server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.107:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ming
    password: ming
#编码格式
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
